# System configuration variables for AmigaOS 4 Python 3.12
build_time_vars = {
    'ABIFLAGS': '',
    'BINDIR': 'python3:bin',
    'BINLIBDEST': 'python3:lib',
    'BUILDPYTHON': 'python3',
    'CC': 'ppc-amigaos-gcc',
    'CFLAGS': '-mcrt=newlib -O2',
    'CONFINCLUDEPY': 'python3:include',
    'DESTDIRS': 'python3:',
    'DESTLIB': 'python3:lib',
    'DESTPATH': '',
    'EXE': '',
    'EXT_SUFFIX': '.so',
    'INCLUDEPY': 'python3:include',
    'LIBDEST': 'python3:lib',
    'LIBDIR': 'python3:lib',
    'MANDIR': 'python3:docs',
    'OPT': '-O2',
    'PLATDIR': '',
    'PLATLIBDIR': 'lib',
    'PYTHONHOME': 'python3:',
    'PYTHONPATH': 'python3:lib',
    'Py_ENABLE_SHARED': 0,
    'SOABI': 'cpython-312-amigaos',
    'VERSION': '3.12',
    'base': 'python3:',
    'installed_base': 'python3:',
    'platbase': 'python3:',
    'platlibdir': 'lib',
    'prefix': 'python3:',
    'userbase': 'python3:',
    'srcdir': 'python3:',
}
